name: falletter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: WantedSans
      fonts:
        - asset: assets/fonts/wanted_sans_extra_bold.ttf
          weight: 800
        - asset: assets/fonts/wanted_sans_bold.ttf
          weight: 700
        - asset: assets/fonts/wanted_sans_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/wanted_sans_medium.ttf
          weight: 500
        - asset: assets/fonts/wanted_sans_regular.ttf
          weight: 400
  assets:
    - assets/icon/